### ISSUE TITLE
New Repo: Manage your AWX / Ansible Automation Platform using Configuration as Code (CasC)

### ISSUE THREAD

**Issue by ivarmu** [redhat-cop/org#452]
### Type of repository request

Creation of a new repository to have published a CasC for AAP/Tower.

### Requested name for the repository

casc-aap

### Repository Description

Manage your AWX / Ansible Automation Platform using Configuration as Code (CasC).

Like to mention the Desired State feature, which is implemented through a schedules controller object type. Basically, it will schedule a recurring execution of the Job Template that applies the changes to the objects in the controller with the tag "desired_state" and the extra_var "desired_state=true". The job will compare the objects that exist in the controller with what exists in the repository, the logic will delete those that are not found as code. Yeap, you're right, in a way is acting as ArgoCD / Openshift GitOps, but for Controller objects and using Ansible.

### Admin Access

@ivarmu
@silvinux

### Write Access

@ivarmu
@silvinux

### Read Access

Name of the team(s) and/or user(s) that should have read access on the newly created repository.

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sean-m-sullivan** [comment]
This should have the galaxy credential that is in the other tower_config/tower_utilities added to this repo as well. So they can publish a collection

**Comment by ericzolf** [comment]
Few questions/remarks:

1. in order to simplify collection handling, the name should be with only letters and underscores
2. also from a consistency perspective, it might make more sense to call it `aap_casc` (or `controller_casc` if it covers only controller aka AWX)
3. @ivarmu @silvinux do I understand/remember it right that your approach is heavily based on controller_configuration? Wouldn't make sense to merge them instead of having them separately? I think we should align in the context of the Automation CoP, what do you think?

**Comment by ivarmu** [comment]
Closing this issue, as we've already merged our content with the controller_configuration collection: https://github.com/redhat-cop/controller_configuration/pull/333
