### ISSUE TITLE
Repo for gitlab-ci job & pipeline templates

### ISSUE THREAD

**Issue by pfeifferj** [redhat-cop/org#561]
### Type of repository request

We already have a repo similar repo for sharing [github actions](https://github.com/redhat-cop/github-actions). I think it would be great to set up something similar & to share gitlab-ci job & pipeline templates. I already have a collection of some universal templates I created for personal projects that I could contribute.

### Requested name for the repository

gitlab-ci-templates

### Repository Description

Collection of GitLab CI templates

### Associated CoP

Container CoP

### Admin Access

I would be interested in maintaining this. If you know of more people who would be interested, by all means add them too :)

### Write Access

tbd

### Read Access

I would advocate for making it public but this can be discussed, of course :)

### Additional details

Any additional information or context to provide for this request.

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by garethahealy** [comment]
@pfeifferj ; the github-actions repo is dog-fooded, i.e.: repos within this org use those actions. if this repo was to be created, who is using these gitlab-ci templates? is it just you? or are they used internally and will have a lifespan, other than one off examples.

I am asking because, typically, we want repos to be active/used by people, and not a place where content is just put and then never used/updated/dies and I am not 100% if this fits that or not.

**Comment by garethahealy** [comment]
@pfeifferj since you are the only one creating the content, doesn't feel like the correct time to move into a CoP repo. if you get more people involved in creating/managing the gitlab content, please re-open and will re-assess.
