### ISSUE TITLE
Create repository for OpenShift IaC - ACM components

### ISSUE THREAD

**Issue by selrahal** [redhat-cop/org#932]
### Type of repository request

Create a new repository

### Requested name for the repository

`openshift-iac-acm`

### Repository Description

This repository containers the ACM automation supporting OpenShift IaC blueprint. 

### Associated CoP

The CoP this repository is associated with.

### Admin Access

@rgoodson-redhat 
@selrahal 
@pkliczewski 

### Write Access

@machacekondra 
@ddreggors 
@bmarlow 
@raffaelespazzoli 

---

Review request:

cc: @redhat-cop/container-cop-core

**Comment by sabre1041** [comment]
@selrahal question for you. For access management, we typically use teams to handle who has permissions to perform capabilities. We can either create a new set of teams focused on IaC or to align with the set of existing flightpath teams.

Otherwise we can create the following teams:

* openshift-iac (top level with read access and include all of the members listed above)
* openshift-iac-admins
* openshift-iac-mergers

Which option do you want to go forward with?

**Comment by selrahal** [comment]
let's use the existing set of flightpath teams, thanks @sabre1041 !!
